In [1]:
import numpy as np

In [2]:
np.array([1,2,3])

array([1, 2, 3])

In [ ]:
"""
        ◘ Numpy is very similar to list
    Now question is I have already a list why should i need numpy.
    Benifits:
     • Less memory
     • fast 
     • Convinient
    
"""

In [5]:
import numpy as np
import time
import sys

In [6]:
l = range(1000)

In [7]:
print(sys.getsizeof(5)*len(l))

28000


In [8]:
array = np.arange(1000)
print(array.size*array.itemsize)

4000


In [125]:
SIZE = 1000
l1 = range(SIZE)
l2 = range(SIZE)


a1=np.arange(SIZE)
a2=np.arange(SIZE)

# python list
start =time.time()
result = [(x+y) for x,y in zip (l1,l2)]
print("python list took : ", (time.time() - start)*1000)

# numpy array
start = time.time()
result = a1 + a2
print ("numpy took : ", (time.time()-start)*1000)



python list took :  0.0
numpy took :  0.0


In [126]:
a1 = np.array([1,2,3])
a2=np.array([4,5,6])
a1+a2

array([5, 7, 9])

### Basic array operations

In [127]:
import numpy as np

In [128]:
a=np.array([5,6,9])

In [129]:
a[1]

6

In [131]:
a[2]

9

In [133]:
a=np.array([[1,2],[3,4],[5,6]])

In [134]:
a.ndim

2

In [135]:
a=np.array([5,6,9])

In [136]:
a.ndim

1

In [137]:
a[1]

6

In [138]:
a.itemsize

4

In [139]:
a.dtype

dtype('int32')

In [144]:
a=np.array([[1,2],[3,4],[5,6]],dtype=np.float64)

In [145]:
a.itemsize

8

In [146]:
a.size

6

In [147]:
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [148]:
a.shape

(3, 2)

In [149]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [150]:
l=range(5)

In [151]:
range(0,5)

range(0, 5)

In [152]:
l[1]

1

In [153]:
l

range(0, 5)

In [154]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [155]:
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

In [156]:
np.linspace(2,5,20)

array([2.        , 2.15789474, 2.31578947, 2.47368421, 2.63157895,
       2.78947368, 2.94736842, 3.10526316, 3.26315789, 3.42105263,
       3.57894737, 3.73684211, 3.89473684, 4.05263158, 4.21052632,
       4.36842105, 4.52631579, 4.68421053, 4.84210526, 5.        ])

In [157]:
a.shape

(3, 2)

In [158]:
a.reshape(2,3)

array([[1., 2., 3.],
       [4., 5., 6.]])

In [159]:
a.ravel()

array([1., 2., 3., 4., 5., 6.])

### Mathematical Functions with numpy

In [161]:
a.min()

1.0

In [162]:
a.max()

6.0

In [163]:
a.sum()

21.0

In [164]:
a.sum(axis=0)

array([ 9., 12.])

In [166]:
a.sum(axis=1)

array([ 3.,  7., 11.])

In [168]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [169]:
np.std(a)

1.707825127659933

In [170]:
a = np.array([[1,2],[3,4]])

In [171]:
b=np.array([[5,6],[7,8]])

In [173]:
a

array([[1, 2],
       [3, 4]])

In [174]:
b

array([[5, 6],
       [7, 8]])

In [175]:
a+b

array([[ 6,  8],
       [10, 12]])

In [176]:
a*b

array([[ 5, 12],
       [21, 32]])

In [177]:
a/b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [178]:
a.dot(b)

array([[19, 22],
       [43, 50]])

In [179]:
import numpy as np

In [180]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [181]:
for row in a:
    for cell in row:
        print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [184]:
for row in a.flatten():
    print(row)

0
1
2
3
4
5
6
7
8
9
10
11


In [185]:
for x in np.nditer(a,order='C'):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [186]:
for x in np.nditer(a,order='F'):
    print(x)

0
4
8
1
5
9
2
6
10
3
7
11


In [187]:
for x in np.nditer(a,order='F',flags=['external_loop']):
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [188]:
for x in np.nditer(a,op_flags=['readwrite']):
    x[...]=x*x

In [189]:
a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [191]:
b = np.arange(3,15,4).reshape(3,1)
b

array([[ 3],
       [ 7],
       [11]])

In [192]:
for x,y in np.nditer([a,b]):
    print(x,y)

0 3
1 3
4 3
9 3
16 7
25 7
36 7
49 7
64 11
81 11
100 11
121 11


### 1. Indexing and Slicing
### 2. Iterating through arrays
### 3. Stacking togather two arrays
### 4. Indexing with boolean arrays

In [193]:
import numpy as np
n = [6,7,8]

In [194]:
n[0:2]

[6, 7]

In [195]:
n[-1]

8

In [196]:
a= np.array([6,7,8])
a[0:2]

array([6, 7])

In [197]:
a[-1]

8

In [198]:
a=np.array([[6,7,8],[1,2,3],[9,3,2]])

In [199]:
a

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [200]:
a[1,2]

3

In [201]:
a[0:2,2]

array([8, 3])

In [202]:
a[-1]

array([9, 3, 2])

In [203]:
a[-1,0:2]

array([9, 3])

In [205]:
a[:,1:3]

array([[7, 8],
       [2, 3],
       [3, 2]])

In [207]:
for x in a:
    print(x)

[6 7 8]
[1 2 3]
[9 3 2]


In [208]:
for cell in a.flat:
    print(cell)

6
7
8
1
2
3
9
3
2


In [209]:
a=np.arange(6).reshape(3,2)
b=np.arange(6,12).reshape(3,2)

In [210]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [211]:
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [212]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [213]:
np.hstack((a,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [215]:
a=np.arange(30).reshape(2,15)

In [216]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [217]:
np.hsplit(a,3)

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]), array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]), array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [218]:
np.vsplit(a,2)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

In [221]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])