In [1]:
import os
os.chdir("C:\\Users\\vikas\\Desktop\\PythonML")

In [2]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt
digits = load_digits()

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target,test_size=0.3)

In [5]:
#to avoid a warning
import warnings
warnings.simplefilter(action='ignore',category=FutureWarning)

In [6]:
#Logistics Regression

lr = LogisticRegression()
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9685185185185186

In [7]:
#SVM

svm = SVC()
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.3648148148148148

In [8]:
#Random Forest


rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9703703703703703

In [9]:
#KFold cross validation
#Basic Example
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [10]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [11]:
#Use KFold for our digits example
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [12]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

scores_logistic = []
scores_svm = []
scores_rf = []

for train_index, test_index in kf.split(digits.data):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                       digits.target[train_index], digits.target[test_index]
    scores_logistic.append(get_score(LogisticRegression(), X_train, X_test, y_train, y_test))  
    scores_svm.append(get_score(SVC(), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))

In [13]:
scores_logistic

[0.8964941569282137, 0.9515859766277128, 0.9115191986644408]

In [14]:
scores_svm

[0.41068447412353926, 0.41569282136894825, 0.4273789649415693]

In [15]:
scores_rf

[0.9365609348914858, 0.9499165275459098, 0.9298831385642737]

In [16]:
#Cross_val_score Function
from sklearn.model_selection import cross_val_score

In [17]:
#Logistic regression model performance using cross_val_score
cross_val_score(LogisticRegression(), digits.data, digits.target)

array([0.89534884, 0.94991653, 0.90939597])

In [18]:
#svm model performance using cross_val_score
cross_val_score(SVC(), digits.data, digits.target)

array([0.39368771, 0.41068447, 0.45973154])

In [20]:
#random forest performance using cross_val_score
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target)

array([0.92857143, 0.95492487, 0.92114094])

In [21]:
#cross_val_score uses stratifield kfold by default
#Parameter tunning using k fold cross validation
scores1 = cross_val_score(RandomForestClassifier(n_estimators=5),digits.data, digits.target, cv=10)
np.average(scores1)

0.8758856131096484

In [22]:
scores2 = cross_val_score(RandomForestClassifier(n_estimators=20),digits.data, digits.target, cv=10)
np.average(scores2)

0.9416357537554086

In [23]:
scores3 = cross_val_score(RandomForestClassifier(n_estimators=30),digits.data, digits.target, cv=10)
np.average(scores3)

0.9472771529478692

In [25]:
scores4 = cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target, cv=10)
np.average(scores4)

0.9461055854859441